export const ADMIN_GET_MEMBER ='ADMIN_GET_MEMBER';
export const ADMIN_DP_CLICK_STYLE ='ADMIN_DP_CLICK_STYLE';
export const ADMIN_ALL_USER ='ADMIN_ALL_USER';
export const ADMIN_SEARCH_USER ='ADMIN_SEARCH_USER';
export const ADMIN_USERCLICK ='ADMIN_USERCLICK';
export const DELETE_ACCOUTN_ADMIN ='DELETE_ACCOUTN_ADMIN';
export const EDIT_ACCOUTN_ADMIN ='EDIT_ACCOUTN_ADMIN';
