export const GET_DATA_FILM = 'GET_DATA_FILM';
export const GET_DATA_FILM_SEARCH = 'GET_DATA_FILM_SEARCH';
export const GET_DATA_CINEMA = 'GET_DATA_CINEMA';
export const GET_DATA_CINEMA_WITH_ID_CINEMA = 'GET_DATA_CINEMA_WITH_ID_CINEMA';
export const GET_DATA_CINEMA_WITH_ID_CINEMA_BHD = 'GET_DATA_CINEMA_WITH_ID_CINEMA_BHD';
export const GET_DATA_FILM_WITH_ID_CINEMA = 'GET_DATA_FILM_WITH_ID_CINEMA';
export const GET_DATA_FILM_LIST_CINEMA = 'GET_DATA_FILM_LIST_CINEMA';